### ISSUE TITLE
Add StringSubject isNotBlank or hasText

### ISSUE THREAD

**Issue by magicprinc** [google/truth#1153]
Please add a very useful and quite common condition to StringSubject:

if string has text == is not blank

I miss it frequently :-(

Example 
- null → doesn't have text == is blank
- "" → doesn't have text == is blank
- " \r \b \n " → doesn't have text == is blank
- "  I am ok! " → has text == is not blank

**Comment by cgdecker** [comment]
We generally recommend that you trim the string in question first if you want to do this, rather than having a separate method for it, e.g.

```
// uses a weird definition of whitespace that doesn't match Unicode's
assertThat(myString.trim()).isEmpty();

// matches Unicode definition of whitespace
assertThat(CharMatcher.whitespace().trimFrom(myString)).isEmpty();
```

We also avoid APIs that treat `null` and non-`null` values equivalently (as you suggest with "`null` -> is blank"). Thanks for the request, but I don't think we'll be adding this.

**Comment by eamonnmcmanus** [comment]
If you only want to check that your string contains zero or more blanks and nothing else, you can use something like
```java
assertThat(string).matches(" *");
```
with `"\\s*"` or `"\\h*"` as alternatives depending on exactly what you want "blank" to mean.
