### ISSUE TITLE
Do calls to Subject.check() lose the failureMessage?

### ISSUE THREAD

**Issue by cpovirk** [google/truth#199]
It looks like they probably do, since they preserve the `failureStrategy` but not the `TestVerb` (which contains the `failureMessage`) as a whole. I apologize for not confirming this before filing.

We probably want to preserve `failureMessage`. We could probably hack that up quickly enough, but maybe this is an opportunity to do a larger review of the relationship between these APIs.

**Comment by cgruber** [comment]
So, withFailureMessage() should never have been a part of TestVerb, though I see how it got that way.  It really should have been part of a stateful implementation of FailureStrategy which is passed along - especially since FailureStrategy is the place where the failure message gets used.  I'm working up a change.

**Comment by cgruber** [comment]
Fixed and fix merged.
