### ISSUE TITLE
add java.net.URI and java.net.URL subjects

### ISSUE THREAD

**Issue by ispringer** [google/truth#246]
I think these would be valuable particularly for methods to check for query param presence or values, e.g.:

```
assertThat(uri).containsQueryParam("foo")
assertThat(uri).containsQueryParam("utm_medium", "email")
```

**Comment by kluever** [comment]
Seems pretty reasonable to me.

**Comment by dinesh707** [comment]
@kluever is this feature already under development ?

**Comment by kluever** [comment]
Internally, we have the following usage counts:
`java.net.URI`: x
`java.net.URL`: 2x
`com.google.common.net.Uri`: 6x

The last one (`Uri`) is an internal only type (which do not plan on open sourcing). We added a `UriSubject` for it about 6 months ago, and unfortunately it hasn't seen much adoption.

When we made the decision to add `UriSubject`, I also proposed adding `URISubject` and `URLSubject`, both of which were shot down (because we don't want to encourage use of those types).

That being said, I don't think we plan on adding support for `URI` or `URL`.
