### ISSUE TITLE
Assertion chaining

### ISSUE THREAD

**Issue by derekpeircesc** [google/truth#253]
Suppose that I have a method that I want to return a non-empty list.

`public List<Object> getList() { ... }`

I know that the method is never supposed to return null, but if it does, I would like a more informative error message than just a `NullPointerException`.

Currently, the solution is this:
```
List<Object> list = getList();
assertThat(list).named("custom name").isNotNull();
assertThat(list).named("custom name").isNotEmpty();
```

This is overly repetitive, especially if the custom name is very long and seeds to be allocated to a local variable.

A better solution would be for `isNotEmpty` and other `ListSubject` methods to give a friendly error message, as `isNotEmpty` implicitly requires `isNotNull`. However, that was apparently dismissed in a much earlier issue.

An alternative would be to chain assertions:
```
List<Object> list = getList();
assertThat(list).named("custom name").isNotNull().isNotEmpty();
```
This would avoid any repetition, and only requires that `isNotNull()` and other assertions return themselves instead of `void`.

Thoughts?

**Comment by kluever** [comment]
In general, we've avoided chaining of assertions for various reasons (decrease in readability of single assertions, trickier failure messages, harder to pin-point lines during failures, etc).

That being said, instead of throwing a NPE, we probably ought to have better failure messages for:
`assertThat(nullList).isNotEmpty();`

**Comment by cpovirk** [comment]
I think that throwing NPE is the right thing because...

`assume().that(nullList).isNotEmpty()`

...should throw an exception to indicate a bug, rather than "fail" (which, for an assumption, means to skip the test).

Did we discuss continuing to throw NPE but giving it a nicer message? I kind of suspect that it will be more trouble than it's worth (since basically every method will need to do an explicit null check). You mentioned an earlier discussion -- do you have a link handy?

**Comment by derekpeircesc** [comment]
Yes, that's the previous issue. In my case, I would like an NPE to be an indication of a failed test rather than a bad test, although I disagree that choosing not to explicitly null-check an object makes a bad test, as it means that you implicitly asserted that the object is not null.

In this case, making the two different assertions, naming each of them, is tedious. Is there currently any better alternative to this?

**Comment by cgruber** [comment]
You may find it tedious, but the trouble of chaining of the sort you
imagine is simply much more trouble than it's worth, as we have discussed
elsewhere.  It confused the API, and made those places where we wanted a
cascading-chain unclear (vs. chaining that simply reused the subject at the
top level.

As to NPE being a failure rather than an error... that is actually not a
problem you have with Truth, but a problem you have with JUnit.  It is
JUnit that interprets only AssertionError subtypes as "failure". Truth
merely reports back whatever you do.  If you throw an NPE from Truth... you
throw it to the runner... Truth doesn't interpret.  If you want that
behavior, that seems like what you want is a different junit runner that
differs in its interpretation of signals.

Or, you could write a very simple extra line of code. :)
