### ISSUE TITLE
hasValue should be equivalent to isEqualTo

### ISSUE THREAD

**Issue by vinaur** [google/truth#254]
[isEqualTo performs deep comparison](https://github.com/google/truth/blob/master/core/src/main/java/com/google/common/truth/PrimitiveIntArraySubject.java#L57) of arrays using Arrays.equals, but [hasValue performs direct comparison](https://github.com/google/truth/blob/master/core/src/main/java/com/google/common/truth/GuavaOptionalSubject.java#L56) via array object's #equals.

Optional&lt;int[]> a = Optional.of(new int[]{1});
int[] b = {1};

assertThat(a.get()).isEqualTo(b); // OK
assertThat(a).hasValue(b); // FAILS

**Comment by cgruber** [comment]
No, it should not.

assertThat(a.get()).isEqualTo(b.get());

is more equivalent to:

assertThat(a).hasValue(b.get());

Also, if a is an absent optional, the secind won't throw whereas the former
will.  b, here, is an optional, not a value referred to by an optional.
 .hasValue() is asking about the content of the optional, not the optional.
 isEqualTo matches like for like.

**Comment by vinaur** [comment]
Sorry, I made a mistake in the initial message. It's been corrected since.

Optional<int[]> a = Optional.of(new int[]{1});

int[] b = {1};


assertThat(a.get()).isEqualTo(b); // OK

assertThat(a).hasValue(b); // FAILS

**Comment by cgruber** [comment]
Of you're using int[] or any primitive int array you might need to be very
careful with assumptions of equality and the like.  I would never use such
a type in an optional and then do tests of equality through the optional.
That seems like a bad idea period.

I would extract the value from the optional and do tests using primitive
arrays subjects.

**Comment by lowasser** [comment]
I think that's the core of the OP's objection: that hasValue isn't overloaded like assertThat and doesn't take into account when normal equality doesn't work.

I don't think it'd be sane to do what they're asking for -- there's a reason all the overloading is done on assertThat -- but I think that's what they want.

**Comment by cgruber** [comment]
Hmm. Tempted to overload .hasValue(Optional<T>), mark it deprecated, and
throw an error indicating that they're doing it wrong.  The problem there
is that technically one could have Optional<Optional<T>>, which this
couldn't differentiate.  Though that possibility makes me gag. :/

**Comment by vinaur** [comment]
I think we're talking past each other. As I mentioned in my reply, I made a
mistake in the original post on github (see the corrected example on
github).

I do not expect #hasValue(Optional<T>) to work the same as #hasValue(T).
The current behavior is fine.

What I do expect to work correctly is
assertThat(Optional<T[]>).hasValue(T[]).this should preform deep
comparison, but it currently does not.

**Comment by cgruber** [comment]
Ahhhhh.  I see.

Unfortunately to do this, i feel like we basically would need to do this
for all collections/map subjects too, and anything that has a contains or
another content checking method that relies on value equality.

Do we want to do this?  We sort of do this for the primitive array
subjects, so it's a semi precedent, but those are special case handlers for
primitive arrays.  Im not sure it's worth it to add primitive array
overloads of hasValue for every type.

**Comment by vinaur** [comment]
It seems like that's more of a question for what `isEqualTo` is supposed to do. IMO `hasValue` should call `isEqualTo` (or whatever helper) to determine equality once the value is unwrapped from the Optional object.

**Comment by vinaur** [comment]
Ah, I see how this works now. I agree that it's a lot of overhead to make this work. I won't push this any further.

**Comment by cpovirk** [comment]
Related: We just added support for `OptionalInt`, etc., and we're adding support for chained assertions on the value, such as:

    assertThat(someOptional).hasValueThat().isGreaterThan(3);

We weren't as excited about adding chaining support for `Optional` itself, given that vanilla `Subject` provides relatively few assertions.[*]

But this issue suggests that there might be some utility to...

    assertThat(someOptionalOfArray).hasValueThat().isEqualTo(someArray);

...in order to get deep array equality.

I'm still unsure whether chaining support is worthwhile, but this use case is worth keeping in mind.

[*] We could consider something that requires a `SubjectFactory`, like...

    assertThat(someOptional).hasValueThat(strings()).contains("foo");

...but it's tricky to name in a fluent style, and it's getting pretty verbose compared to just calling `get`.

**Comment by cpovirk** [comment]
Correction: My snippet...

    assertThat(someOptionalOfArray).hasValueThat().isEqualTo(someArray);

...wouldn't provide deep array equality today anyway, because `hasValueThat()` returns a plain `Subject`. That said, `Subject.isEqualTo` already contains the magic that treats `0` and `0L` as equal. It could in principle contain the logic that treats `new Object[0]` and `new Object[0]` as the same, too. (Currently that logic is in the array subtypes.)

But of course we're still comparing...

    assertThat(someOptionalOfArray).hasValueThat().isEqualTo(someArray);

...to...

    assertThat(someOptionalOfArray.get()).isEqualTo(someArray);

...and arguably users are better off with the latter.

**Comment by cpovirk** [comment]
(since, e.g., custom subjects might override `isEqualTo`. I'm not sure that that's a good idea in general, but it could be nice for subclasses to provide a better failure message. Or maybe, if we really want that, Truth should be providing a failure-message hook for those subclasses to override....)

**Comment by cpovirk** [comment]
(Oh, and the broader point is that chaining subjects have turned out to be weird in various ways, so we don't want to encourage them except in limited circumstances.)

**Comment by cpovirk** [comment]
And the even broader point is "maybe we shouldn't have added `hasValue` at all," given that:

- It can't provide any better a failure message that you'd get from calling `get()` (excluding cases in which you set a failure message).
- It's longer.
- It invites people to mismatch numeric types, etc. (I see quite a few calls like `hasValue(100L)`. Probably those people had a Bad Time when they initially wrote `hasValue(100)`. At least we offer debugging help in our failure messages nowadays, and someday we should add static analysis.)

On the other hand, it's convenient (and very, very widely called inside Google). I don't have a philosophy on what kinds of conveniences are worthwhile in Truth.

**Comment by dimo414** [comment]
Personally, I'm not a fan of `.hasValueThat()`, and I'd like to make it go away. I think it's appealing from users' perspective because it's nice and fluent, but it really doesn't result in any better of an error message than `assertThat(myOptional.get())...`, and it drastically increases the API surface area.

I don't have as strong of an opinion about `.hasValue()` - offhand I think it's fine, but maybe there's a case to be made that it, too, should go away in favor of calling `.get()` directly.

    assertThat(myOptional).isPresent();
    assertThat(myOptional.get()).isEqualTo(...);

It's longer to be sure, but there's limited room for errors. And in many cases the first line isn't necessary since `.get()` will fail all the same. All other things being equal I think I'd want to point people towards:

    assertThat(myOptional.get()).isEqualTo(...);

before

    assertThat(myOptional).hasValue(...);

**Comment by cpovirk** [comment]
Random thoughts on the "philosophy" question:

- Because `Optional` is so common, we're more likely to see assertions that both are about `Optional` and set a failure message. That might argue that it's worth including the convenience method so that users get the nice failure message.
- But it might also mean that we should be extra afraid of the `300` vs. `300L` problem. (Other convenience methods, by contrast, could be immune to this problem if they operate on values that can't be primitives/arrays -- or if they operate _only_ on those types of values (like `hasSize(int)`).)
- The mere existence of `hasValue` does at least slightly suggest that it's "better than" `get`...`isEqualTo`. (I can imagine someone proposing static analysis to suggest users migrate from one to the other.)
- Perhaps `Optional` itself is "special," since it's basically a stand-in for `null`. Like, I can understand saying that an assertion about a field of a protocol buffer is about a "part" of the protocol buffer, but an assertion about the value of an `Optional` isn't about "part" of the `Optional`. I guess I could argue that a single convenience method on `Optional` isn't bad because it's a single method on one (well, two, thanks to JDK `Optional` vs. Guava) type. That is, we're not setting a precedent that any type with _n_ "parts" should offer _n_ assertions on its subject. On the other hand, a type with _n_ parts is arguably a _better_ case for offering helpers, since it means that the failure message could offer the other values as context.... So I think I'm making more of a theoretical argument about `Optional` as special than an actual argument based on the number of "parts."

On a totally different note, I think I failed to mention that adding magic to `hasValue` is not very hard: `check().that(actual).isEqualTo(expected)` should get us part of the way there. That won't solve the array problem that prompted this bug report, but it would solve the analogous integer problem, and, as noted earlier, we could change `Subject.isEqualTo` to contain the array logic, too.

All that said, cgruber makes a good point about that we would be patching over only one instance of the problem. It still comes up with `IterableSubject`, etc. We try to help there with verbose failure messages (and hopefully someday with static analysis), but we're unlikely to change behavior (especially with cases like `Map` (and perhaps `Optional<Optional<...>>`, though I suppose we could special-case _`Optional`_ in `Subject.isEqualTo`, too...) as cgruber again mentions). Perhaps the argument here again comes back to philosophy -- whether `Optional` is special enough (thanks to its ubiquity, its role as "a substitute for `null`", or whatever).

**Comment by cpovirk** [comment]
(We ended up making these equivalent, for better or for worse.)
