### ISSUE TITLE
Prevent incorrect use of assertThat(foo == 42)

### ISSUE THREAD

**Issue by shtratos** [google/truth#298]
I've noticed that some of my team members use `assertThat(Boolean)` incorrectly:
e.g.
```
assertThat(foo == 42);
```
instead of 
```
assertThat(foo).isEqualTo(42);
```
or at least
```
assertThat(foo == 42).isTrue();
```

I admit that it can look right for people quite new to Java.

I wonder if there's a way to fail tests on this kind of usage so that it's caught at build time instead of code reviews.

**Comment by cpovirk** [comment]
If you build with [Error Prone](http://errorprone.info/), it will catch this as part of its [`CheckReturnValue`](http://errorprone.info/bugpattern/CheckReturnValue) check, which [we opt into](https://github.com/google/truth/blob/9cfceb957c0e42b76ca598c07900414081a81144/core/src/main/java/com/google/common/truth/package-info.java#L28). Error Prone is great for lots of other reasons, too :) It would be nice if we had a solution that didn't require it, but that's tough to do.

**Comment by shtratos** [comment]
Yeah, Intellij IDEA highlights it as an issue too.

**Comment by RichardBradley** [comment]
FYI, the current version of Findbugs, 3.0.1, appears to need the `@CheckReturnValue` annotation to be applied to each method, rather than per-package.

c.f. AssertJ, who have applied this annotation to every single one of their methods: https://github.com/joel-costigliola/assertj-core/pull/695

I suppose this is really a bug in Findbugs rather than in Truth. I'll look into raising it there.

**Comment by kluever** [comment]
Thanks @RichardBradley - please crosslink the FindBugs issue here. We'd really like to avoid adding `@CheckReturnValue` back to each method.

**Comment by shtratos** [comment]
I think original FindBugs is dead. One of maintainers forked it as spot bugs https://github.com/spotbugs/spotbugs/

**Comment by RichardBradley** [comment]
Thanks, Findbugs does seem to be abandoned. There hasn't been an official announcement as such, just complete radio silence for 2 years.

Their project page is still up, and [the owner commented about a year ago](https://news.ycombinator.com/item?id=12885549) that he was going to try again, but nothing since then. Perhaps it will revive in the future.

I have raised an issue with the presumptive successor project, Spotbugs: https://github.com/spotbugs/spotbugs/issues/429
