### ISSUE TITLE
ProtoTruth: Incompatible with protobuf 2.5 with `FieldDescriptor.isMapField()` method not found

### ISSUE THREAD

**Issue by timothybasanov** [google/truth#520]
ProtoTruth is generally compatible with Protobuf version 2.5.
But in some edge cases it does not quite work due to missing methods.

```java
java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$FieldDescriptor.isMapField()Z

	at com.google.common.truth.extensions.proto.ProtoTruthMessageDifferencer.diffMessages(ProtoTruthMessageDifferencer.java:171)
	at com.google.common.truth.extensions.proto.ProtoTruthMessageDifferencer.diffMessages(ProtoTruthMessageDifferencer.java:144)
	at com.google.common.truth.extensions.proto.ProtoSubject.isEqualTo(ProtoSubject.java:144)
```

This is due to this line in `ProtoTruthMessageDifferencer`:
```java
        if (fieldDescriptor.isMapField()) {
```

When I know that I'm running against version 2.5 I can do this instead, but it requires source code patching:
```java
        if (false) {
```

It would be nice if ProtoTruth would verify if `FieldDescriptor.isMapField()` method exists and only call it then. Something along these lines if we're trying to avoid Java reflection:

```java
        // FieldDescriptor.isMapField() is absent in Protobuf 2.5, reimplement it without reflection
        FieldDescriptor mapEntryDescriptor =
                fieldDescriptor.getOptions().getDescriptorForType().findFieldByName("mapEntry");
        Object mapEntry = null;
        if (mapEntryDescriptor != null) {
            mapEntry = fieldDescriptor.getOptions().getField(mapEntryDescriptor);
        }
        if ((mapEntry instanceof Boolean) && (boolean)mapEntry) {
```

I'm not qualified enough to make a real code patch against ProtoTruth, but I hope you can help me with that. Thank you in advance.

**Comment by gabrieljones** [comment]
I am running into issues around the get<field>Bytes method being private
when SingularStringFieldAccessor is constructed and calls GeneratedMessage.getMethodOrDie for GeneratedMessage.getDescriptorForType

This results in a ExceptionInInitializerError caused by RuntimeException: Generated message class "xxxxxx" missing method "getXXXXXBytes".

I think this is related:
https://groups.google.com/forum/#!topic/protobuf/HtNHEyT1pKk

I guess I'll have to get this build to start using protoc 3 instead of protoc 2.4.1

**Comment by kluever** [comment]
This sounds like a general library version mismatch problem / diamond dependency issue.

I'm not sure there's much we can do from Truth's perspective.
