### ISSUE TITLE
Could not resolve com.google.code.findbugs:jsr305:3.0.2, required by truth

### ISSUE THREAD

**Issue by carstenhag** [google/truth#525]
Since adding `androidx.test.ext:truth:1.1.0` to my app/build.gradle file, I cannot build my test app anymore.

```
   > Could not resolve com.google.code.findbugs:jsr305:3.0.2.
     Required by:
         project :app > androidx.test.ext:truth:1.1.0 > com.google.guava:guava:26.0-android
      > Cannot find a version of 'com.google.code.findbugs:jsr305' that satisfies the version constraints:
           Dependency path 'regex-crossword-kotlin:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.1.1' --> 'com.google.code.findbugs:jsr305:2.0.1'
           Constraint path 'regex-crossword-kotlin:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 2.0.1}' because of the following reason: debugRuntimeClasspath uses version 2.0.1
           Constraint path 'regex-crossword-kotlin:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 2.0.1}' because of the following reason: debugRuntimeClasspath uses version 2.0.1
           Dependency path 'regex-crossword-kotlin:app:unspecified' --> 'com.github.facebook.stetho:stetho:6d148f20b96ecb29320cced6617830eda8af0426' --> 'com.google.code.findbugs:jsr305:2.0.1'
           Constraint path 'regex-crossword-kotlin:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 2.0.1}' because of the following reason: debugRuntimeClasspath uses version 2.0.1
           Constraint path 'regex-crossword-kotlin:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 2.0.1}' because of the following reason: debugRuntimeClasspath uses version 2.0.1
           Constraint path 'regex-crossword-kotlin:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 2.0.1}' because of the following reason: debugRuntimeClasspath uses version 2.0.1
```

**Comment by carstenhag** [comment]
repositories {
        google()
        jcenter()
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url 'https://maven.google.com/' }
        maven { url 'https://jitpack.io' }
    }

**Comment by cgruber** [comment]
So, oddly, you aren't including the master maven release repository in any of your repositories.  The dep exists in `http://central.maven.org/maven2/` a.k.a. `https://oss.sonatype.org/content/repositories/releases/`

I'm not sure why some deps are in `jcenter()` and some aren't, but this one isn't for some reason.

It's also not in `google()` because, despite the groupId, it's not a google project, it's a project that was hosted on googlecode when that was a thing, and a lot of people used `com.google.code.wahtever` as a groupId. To make this work, you need to use the standard maven repo.

**Comment by friederikewild** [comment]
Also getting these errors during my UI tests after adding `androidTestImplementation "androidx.test.ext:truth:1.1.0"` and same for `androidTestImplementation "com.google.truth:truth:0.44"`

@cgruber My repositories list does include `mavenCentral()` plus the above mentioned `google()` + `jcenter()`. So your suggestion doesn't solve the issue for me. Or is there a different maven repository required?

Already tried to add `com.google.code.findbugs:jsr305:3.0.1` or `guava` as explicit `androidTestImplementation` dependencies without luck.

**Comment by cpovirk** [comment]
We don't have a lot of Gradle expertise. I recommend [asking on StackOverflow](https://stackoverflow.com/questions/tagged/google-truth).

**Comment by yingding** [comment]
this issue might be closed, i just want to add a hint since i still get this issue. I managed to solve it with pin the old `com.google.code.findbugs:jsr305:2.0.1` version.
```console
    androidTestImplementation "com.google.code.findbugs:jsr305:2.0.1"
    androidTestImplementation ('androidx.test.ext:truth:1.1.0') {
        exclude group: "com.google.code.findbugs", module: "jsr305"
    }
```
It seems like the `androidx.test.espresso:espresso-core:3.2.0` and `com.facebook.stetho:stetho:1.5.1` in my case are the libs using the 2.0.1 version of findbugs. And truth lib is the only one moved to findbugs:3.0.2.

In your individual case, you shall check which version are in conflict.

**Comment by mochadwi** [comment]
> this issue might be closed, i just want to add a hint since i still get this issue. I managed to solve it with pin the old `com.google.code.findbugs:jsr305:2.0.1` version.
> 
> ```
>     androidTestImplementation "com.google.code.findbugs:jsr305:2.0.1"
>     androidTestImplementation ('androidx.test.ext:truth:1.1.0') {
>         exclude group: "com.google.code.findbugs", module: "jsr305"
>     }
> ```
> 
> It seems like the `androidx.test.espresso:espresso-core:3.2.0` and `com.facebook.stetho:stetho:1.5.1` in my case are the libs using the 2.0.1 version of findbugs. And truth lib is the only one moved to findbugs:3.0.2.
> 
> In your individual case, you shall check which version are in conflict.

awesome, I've a similar problem with yours. Using `espresso-core` and `stetho`. this fixed my issue
