### ISSUE TITLE
Add factory method to turn a Comparator into a Correspondence

### ISSUE THREAD

**Issue by vRallev** [google/truth#534]
`Correspondence.from(..)` only accepts a `BinaryPredicate`. An overloaded factory method that accepts a `Comparator` would be very helpful. 

For Kotlin users an extension function for the transformation is trivial.
```kotlin
  fun <T> Comparator<T>.toBinaryPredicate(): BinaryPredicate<T, T> {
    return BinaryPredicate { actual, expected -> compare(actual, expected) == 0 }
  }
```
The missing factory method is more annoying in Java.

**Comment by jbduncan** [comment]
Have you tried `Correspondence.from(comparator::compare`? :)

**Comment by vRallev** [comment]
As far as I can tell this doesn't work, because `compare` returns an integer and not a boolean.

**Comment by jbduncan** [comment]
Oh oops, you're right! The fact that `Comparator::compare` returns an integer rather than a boolean catches me often. :)

I think I got confused with Guava's `Equivalence`, which either implements `BiPredicate` or has a method that's compatible with `BiPredicate`.

**Comment by jbduncan** [comment]
So I agree that a method that accepts `Comparator` (or at least `BiFunction<T, T, Integer>` or equivalent) would make `Correspondence` easier to use.

**Comment by cpovirk** [comment]
A question for you: Do you have _existing_ Comparators that you'd like to convert to Correspondences? I'm not sure if we've seen that in our surveys (aside from someone using the natural order for `BigDecimal`). The thing we have seen is people creating Comparators solely for the purpose of passing to a Comparator-to-Correspondence adapter that they write, presumably because methods like `thenComparing` are so nice. [Truth 0.43](https://github.com/google/truth/releases/tag/release_0_43) did add some convenient static factory methods, but they aren't as convenient as `thenComparing`. The unfortunate thing is that many of the Comparators that people write violate the contract for Comparator -- which is fine for this purpose but doesn't give us warm fuzzies, especially since we can imagine static analysis that might flag such problems.

**Comment by vRallev** [comment]
Yes, we had these Comparators, but I think only 2. That's definitely not often for the size of the codebase. I agree with your points.

**Comment by cpovirk** [comment]
Closing, but I'm sure we'll hear about this again, and we can reevaluate if we find some patterns where it's a clear win.
