### ISSUE TITLE
UsingCorrespondence error message includes "exactly one element %s" which makes no sense in most contexts. 

### ISSUE THREAD

**Issue by cgruber** [google/truth#538]
When using my field-by-field reflective correspondence (don't ask, it's an assertJ migration thing), which has a toString() of "has fields which match those of", and then executing the following:
```
assertThat(actual).comparingElementsUsing(fieldByField).containsExactly(a, b, c)
```
the error message is (shortening long `toString()`s):
```
Not true that <A1, B1, C1> contains exactly one element that has fields which match
those of each element of <A2, B2, C2>. It is missing an element that has fields which
match those of <A2> and has unexpected elements <A1>
```

The above error happens whether there is zero, one, two, or many elements in "containsExactly" (or containsExactlyElementsIn).  The construction of the error messages includes the "exactly one element" bit, which seems inaccurate to the meaning of the method. 

Getting the right language is a bit awkward, in order to make the first use of the correspondence's `toString()` work with the second, but ti could be something like.

```
Not true that <A1, B1, C1> contains exactly elements such that each that has fields
which match those of each element of <A2, B2, C2>. It is missing an element that
has fields which match those of <A2> and has unexpected elements <A1>
```

Looking through the code, there are a few combinations of this, where "one element" is used, and hard-coded in.  It should either be less hard-coded, or generally replaced with suitable language. 

The logic is right, but the error ends up being confusing, no matter how you phrase the `Correspondence`'s `toString()``

**Comment by cgruber** [comment]
Related, the use of `Correspondence.toString()` here is a bit linguistically frustrating, in that I can see it being frustrating to supply the same verbiage for singular and plural cases, so ending up with language like `it is missing elements that has fields` because I can't adjust the message between "has" and "have".

Yeah, plural agreement in english is shitty, but at least it's a boolean choice.

So... related to the above issue, is this side-issue, which is that toString() probably isn't the correct choice here.  Having a `pluralMessageFragment()` and `singularMessageFragment()`.   That or figure out some phrasing that allows the same in plural or singular (but honestly, I don't think that's possible).

**Comment by cpovirk** [comment]
@PeteGillin, who I'm sure is all too familiar with the difficulty of phrasing these methods :)

I do hope someday to migrate these messages to the new key-value style, which would mean something more like plain `IterableSubject`, e.g.,

```
missing (1)   : A2
unexpected (1): A1
comparison    : has fields which match those of
---
expected      : A1, B1, C1
but was       : A2, B2, C2
```

That would simultaneously mess up users' existing carefully constructed messages yet at least give users a simpler template to fit their messages into.

**Comment by PeteGillin** [comment]
Ugh, yes. As @cpovirk says, getting the English grammar right around this is hard. This isn't the only place which has come to my attention where it's not quite right.

This will be fixed one way or the other when we make the jump to key-value style messages. I'm a little bit more optimistic that we can do this in a way that gives us good grammar in most cases. For example, the `comparison` key could have a value like `actual element has fields which match those of expected element` instead (the extra verbiage is a good thing where the correspondence is not symmetric because it makes the requirement more clear, I think). I _thing_ that's good in all the cases I'm aware of, but we need to double-check.

I don''t think we're going to fix it before that. I have other reasons for wanting to make that jump soon-ish. And I'd really rather not make two changes to the messages when we could make one, because it turns out that quite a lot of folks (at least within our own codebase, and quite possibly externally too) use this functionality to write test helpers, and they have unit tests for those helpers which assert on the failure messages, and those tests all fail any time we change anything (so internally we're kind-of obliged to fix those tests, because saying "we told you in some obscure corner of the docs not to rely on this" is kind of mean; externally, we're creating toil for our users). So I think we should just live with the current slight awkwardness for a little bit longer, if everyone is okay with that.

**Comment by cpovirk** [comment]
This happened in https://github.com/google/truth/commit/dda41ff8e4bb65753f9d9f3dd0ec46fb7c57aa07

Hopefully we'll do a release before the end of the quarter so that people can actually benefit.
