### ISSUE TITLE
Allow logical operations on assertions

### ISSUE THREAD

**Issue by nakulj** [google/truth#991]
It would be nice if there was some way of performing logical operations on assertions, whether fluently or not.

```java
// fluent version
assertThat(foo).isEqualTo(3).orThat(bar).isEqualTo(5);

assertAtLeastOneOf(
  that(foo).isEqualTo(3),
  that(bar).isEqualTo(4)
);
```

**Comment by amalloy** [comment]
The fluent version would be a very big API change to pretty much every Subject. It couldn't work as you propose, because `isEqualTo(3)` has to throw an exception for non-3 subjects. I don't expect we would make a change like that anytime soon.

I see no huge technical barriers to implementing `assertAtLeastOneOf`, but it doesn't seem like a hugely important feature to have. A disjunction like this would tend to be useful only in tests that are already complicated enough to merit some concern (since tests should be simple). And in the worst case, you can emulate this behavior with an assertion on ordinary booleans.

**Comment by cpovirk** [comment]
> a bunch of custom that(...) methods that counted how many assertions had been performed (so that you can compare that to the number of failures)

That assumes that callers perform a single assertion per `that(...)` call. That's _almost_ always going to be a reasonable assumption: Few users are going to write...

```java
StringSubject a = holds.that(myString);
a.startsWith("http:");
a.startsWith("https:");
```

...when they could just write...

```java
holds.that(myString).startsWith("http:");
holds.that(myString).startsWith("https:");
```

But we could imagine seeing multiple assertions on the same `Subject` instance in the case of Kotlin users, as discussed in #572.

**Comment by nakulj** [comment]
> Fuzzy Truth for single objects.

I think this is actually what I really wanted :) 
I understand that failure messaging for fuzzy truth is hard- but it would be nice for it to be handled once, at the library level, rather than multiple times by everyone who writes a fuzzy test.
